name: Build and Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.Js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Angular Cli globally
      run: npm install -g @angular/cli

    - name: Install Node Dependencies
      run: npm ci
      working-directory: Client

    - name: Build Angular app
      run: ng build
      working-directory: Client

    - name: Set up JDK
      uses: actions/setup-java@v3.11.0
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package -DskipTests
      working-directory: Server

    - name: Create static directory
      run: mkdir -p Server/src/main/resources/static

    - name: Copy Angular build files to Server static directory
      run: |
        cp -r Client/dist/* Server/src/main/resources/static/

    - name: Install Railway CLI
      run: npm i -g @railway/cli

    - name: Deploy to Railway
      run: railway up
      working-directory: Server
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}